<?php

/**
 * @file
 * Module to create Islandora objects using the Feeds contrib module.
 */

/**
 * Implements hook_feeds_plugins().
 */
function islandora_feeds_feeds_plugins() {
  $info = array();
  $info['IslandoraFeedsFeedsNodeProcessor'] = array(
    'name' => 'Islandora Feeds node processor',
    'description' => 'Creates Islandora objects. Corresponding nodes are not created.',
    'handler' => array(
      'parent' => 'FeedsProcessor',
      'class' => 'IslandoraFeedsFeedsNodeProcessor',
      'file' => 'IslandoraFeedsFeedsNodeProcessor.inc',
      'path' => drupal_get_path('module', 'islandora_feeds'),
    ),
  );
  return $info;
}

/**
 * Implements hook_action_info().
 *
 * @todo: This action ingests Islandora objects at a point later
 * in time than the Feed import, so we need to store the target
 * collection and content model. Do we require the user to create
 * fields with a specific name in their template content type?
 */
function islandora_feeds_action_info() {
  return array(
    'islandora_feeds_create_islandora_objects' => array(
      'type' => 'node',
      'label' => t('Create Islandora objects from nodes'),
      'configurable' => TRUE,
      'behavior' => array('changes_property'),
      'triggers' => array('node_presave', 'node_insert', 'node_update'),
    ),
  );
}

/**
 * Query the resource index to get a list of collections or content
 * models.
 *
 * @param $type string
 *  Either 'collections' or 'cmodels'.
 *
 * @return array
 *   List of PIDs corresponding to the collections or content models.
 */
function islandora_feeds_get_collections_or_content_models($type) {
  $types = array(
    'collections' => 'islandora:collectionCModel',
    'cmodels' => 'fedora-system:ContentModel-3.0'
  );
  $type_for_query = '<info:fedora/' . $types[$type] . '>';
  // Query the rindex to get all collections.
  $tuque = islandora_get_tuque_connection();
  $ri_query = "select \$object \$label from <#ri>
     where \$object <fedora-model:hasModel> $type_for_query
      and \$object <fedora-model:label> \$label";
  $results = $tuque->repository->ri->itqlQuery($ri_query, 'unlimited');
  $ret = array();
  foreach ($results as $member) {
    $pid = preg_replace('/info:fedora\//', '', $member['object']['value']);
    $label = $member['label']['value'];
    // We don't want the root collection.
    if ($pid == 'islandora:root') {
      $label = 'Islandora Root Collection';
    }
    $ret[$pid] = $label;
  }
  return $ret;
}

