<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

  <xsd:annotation>
    <xsd:documentation xml:lang="en">
     @todo: Add provenance info like this:
     Generated by the Islandora Feeds module.
     Wed, 25 Sep 2013 15:28:57 -0700
    </xsd:documentation>
  </xsd:annotation>

  <!-- @todo: 'islandora_stub' is the content type's machine name. -->
  <xsd:element name="islandora_stub" type="IslandoraStubType"/>

  <!-- @todo: For each field in the content type, add an xsd:element as follows. -->
  <xsd:complexType name="IslandoraStubType">
    <xsd:sequence>
      <xsd:element name="name"   type="xsd:string"/>
      <xsd:element name="street" type="xsd:string"/>
      <xsd:element name="city"   type="xsd:string"/>
      <xsd:element name="state"  type="xsd:string"/>
      <xsd:element name="zip"    type="xsd:decimal"/>
    </xsd:sequence>
  </xsd:complexType>

</xsd:schema>
